CREATE TABLE IF NOT EXISTS parts_list_no_response_dismissals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id INTEGER NOT NULL UNIQUE,
    dismissed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_no_response_email
ON parts_list_no_response_dismissals(email_id);
